
python main.py \
    --model_name CLARRec \
    --data_name Baby  \
    --data_dir data/10core \
    --context encoder \
    --seq_representation_type mean \
    --attention_type None \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Main_Table/10core/SASRec/Baby \
    --model_idx Mean \
    --contrast_type None \
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 2\
    --intent_cf_weight 1.2\
    --cf_weight 0 \
    --cluster_value 0.3 \

python main.py \
    --model_name CLARRec \
    --data_name Clothing_Shoes_and_Jewelry  \
    --data_dir data/10core \
    --context encoder \
    --seq_representation_type mean \
    --attention_type None \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Main_Table/10core/SASRec/Clothing_Shoes_and_Jewelry \
    --model_idx Mean \
    --contrast_type None\
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 2\
    --intent_cf_weight 1.2\
    --cf_weight 0 \
    --cluster_value 0.3 \

python main.py \
    --model_name CLARRec \
    --data_name Beauty  \
    --data_dir data/10core \
    --context encoder \
    --seq_representation_type mean \
    --attention_type None \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Main_Table/10core/SASRec/Beauty \
    --model_idx Mean \
    --contrast_type None\
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 2\
    --intent_cf_weight 1.2\
    --cf_weight 0 \
    --cluster_value 0.3 \

python main.py \
    --model_name CLARRec \
    --data_name Grocery_and_Gourmet_Food  \
    --data_dir data/10core \
    --context encoder \
    --seq_representation_type mean \
    --attention_type None \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Main_Table/10core/SASRec/Grocery_and_Gourmet_Food \
    --model_idx Mean \
    --contrast_type None\
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 2\
    --intent_cf_weight 1.2\
    --cf_weight 0 \
    --cluster_value 0.3 \

python main.py \
    --model_name CLARRec \
    --data_name Home_and_Kitchen  \
    --data_dir data/10core \
    --context encoder \
    --seq_representation_type mean \
    --attention_type None \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Main_Table/10core/SASRec/Home_and_Kitchen \
    --model_idx Mean \
    --contrast_type None\
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 2\
    --intent_cf_weight 1.2\
    --cf_weight 0 \
    --cluster_value 0.3\
    --max_seq_length 60\

python main.py \
    --model_name CLARRec \
    --data_name Toys_and_Games  \
    --data_dir data/10core \
    --context encoder \
    --seq_representation_type mean \
    --attention_type None \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Ablation/Beauty/Item_level/Max_seq/70 \
    --model_idx Mean\
    --contrast_type Item-Level \
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 2\
    --intent_cf_weight 1.2\
    --cf_weight 0 \
    --cluster_value 0.3\
    --max_seq_length 70\

# scripts/Beauty/2.sh