python main.py \
    --model_name="UPTRec" \
    --data_name="Beauty"  \
    --output_dir="output_custom/Beauty" \
    --contrast_type="IntentCL" \
    --seq_representation_type="concatenate" \
    --attention_type="Cluster" \
    --augment_type="mask" \
    --model_idx="UPTRec_Clustered_Attention_IntentCL" \
    --num_intent_clusters=32 \
    --gpu_id=1\ --epochs=2000\ --patience=500\ --batch_size=512\ --de_noise\ 