python main.py \
    --model_name UPTRec \
    --data_name Beauty  \
    --data_dir data/ \
    --context encoder \
    --seq_representation_type mean \
    --attention_type Cluster \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Ablation/Beauty/Item_level/Invariant_Aug/Base\
    --model_idx Mean \
    --contrast_type Item-Level \
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 10\
    --intent_cf_weight 1 \
    --cf_weight 1 \
    --cluster_value 0.3 \
    --invariant_augment \
    --num_hidden_layers 3 \
    --pre_train \

python main.py \
    --model_name UPTRec \
    --data_name Beauty  \
    --data_dir data/ \
    --context encoder \
    --seq_representation_type mean \
    --attention_type Cluster \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Ablation/Beauty/Item_level/Invariant_Aug/Bi-direction\
    --model_idx Mean \
    --contrast_type Item-Level \
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 10\
    --intent_cf_weight 1 \
    --cf_weight 1 \
    --cluster_value 0.3 \
    --invariant_augment \
    --num_hidden_layers 3 \
    --bi_direction \
    --pre_train \

python main.py \
    --model_name UPTRec \
    --data_name Beauty  \
    --data_dir data/ \
    --context encoder \
    --seq_representation_type mean \
    --attention_type Cluster \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Ablation/Beauty/Item_level/Invariant_Aug/NCL\
    --model_idx Mean \
    --contrast_type Item-Level \
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 10\
    --intent_cf_weight 1 \
    --cf_weight 1 \
    --cluster_value 0.3 \
    --invariant_augment \
    --num_hidden_layers 3 \
    --ncl \
    --pre_train \

python main.py \
    --model_name UPTRec \
    --data_name Beauty  \
    --data_dir data/ \
    --context encoder \
    --seq_representation_type mean \
    --attention_type Cluster \
    --cluster_joint \
    --de_noise \
    --batch_size 256 \
    --epochs 2000 \
    --gpu_id 0 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir Ablation/Beauty/Item_level/Invariant_Aug/Cluster_tempearture\
    --model_idx Mean \
    --contrast_type Item-Level \
    --warm_up_epoches 0\
    --rec_weight 1 \
    --temperature 1 \
    --num_intent_clusters 10\
    --intent_cf_weight 1 \
    --cf_weight 1 \
    --cluster_value 0.3 \
    --invariant_augment \
    --num_hidden_layers 3 \
    --cluster_temperature \
    --pre_train \


# ./scripts/Beauty/test.sh