
python main.py \
    --model_name UPTRec \
    --data_name Beauty  \
    --context encoder \
    --seq_representation_type concatenate \
    --attention_type Cluster \
    --cluster_joint \
    --de_noise \
    --batch_size 512 \
    --epochs 2000 \
    --gpu_id 1 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir output/Beauty/Item_description_level/V2_CL_03\
    --model_idx V2_CL_03\
    --contrast_type Item-description \
    --augment_type random \
    --n_views 2 \
    --cluster_train 1 \
    --warm_up_epoches 0\
    --num_intent_clusters 10 \
    --intent_cf_weight 0.01 \
    --cf_weight 1 \
    --description \
    --cluster_temperature \
    --cluster_value 0.3 \
    --num_user_intent_clusters 256 \
    --intent_cf_user_weight 0.01 \
    --temperature 1 \
    --cf_weight 1 \
    --align_weight 0.01 \

python main.py \
    --model_name UPTRec \
    --data_name Beauty  \
    --context encoder \
    --seq_representation_type concatenate \
    --attention_type Cluster \
    --cluster_joint \
    --de_noise \
    --batch_size 512 \
    --epochs 2000 \
    --gpu_id 1 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir output/Beauty/Item_description_level/V2_CL_04\
    --model_idx V2_CL_04\
    --contrast_type Item-description \
    --augment_type random \
    --n_views 2 \
    --cluster_train 1 \
    --warm_up_epoches 0\
    --num_intent_clusters 10 \
    --intent_cf_weight 0.01 \
    --cf_weight 1 \
    --description \
    --cluster_value 0.3 \
    --num_user_intent_clusters 256 \
    --intent_cf_user_weight 0.01 \
    --temperature 1 \
    --cf_weight 1 \
    --align_weight 0.01 \

python main.py \
    --model_name UPTRec \
    --data_name Beauty  \
    --context encoder \
    --seq_representation_type concatenate \
    --attention_type Cluster \
    --cluster_joint \
    --batch_size 512 \
    --epochs 2000 \
    --gpu_id 1 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir output/Beauty/Contrastive_Learning/User_level/V2_CL_05 \
    --model_idx V2_CL_05\
    --contrast_type User \
    --n_views 2 \
    --num_intent_clusters 10 \
    --cluster_train 1 \
    --warm_up_epoches 0\
    --intent_cf_weight 0.01 \
    --cf_weight 1 \
    --cluster_value 0.3 \
    --intent_cf_user_weight 0.1 \
    --num_hidden_layers 1 \
    --cluster_temperature \
    --cluster_prediction \
    --temperature 1 \
    --de_noise \

python main.py \
    --model_name UPTRec \
    --data_name Beauty  \
    --context encoder \
    --seq_representation_type concatenate \
    --attention_type Cluster \
    --cluster_joint \
    --de_noise \
    --batch_size 512 \
    --epochs 2000 \
    --gpu_id 1 \
    --visualization_epoch 20 \
    --patience 30 \
    --embedding \
    --output_dir output/Beauty/Item_User_level/V2_CL_05\
    --model_idx V2_CL_05\
    --contrast_type Item-User \
    --augment_type random \
    --n_views 2 \
    --cluster_train 1 \
    --warm_up_epoches 0\
    --num_intent_clusters 10 \
    --intent_cf_weight 0.01 \
    --cf_weight 1 \
    --num_hidden_layers 1 \
    --cluster_value 0.3 \
    --cluster_temperature \
    --num_user_intent_clusters 256 \
    --intent_cf_user_weight 0.01 \
    --temperature 1 \

# scripts/Beauty/UPTRec_gpu_1.sh