wandb_version: 1

data_dir:
  desc: null
  value: data/
output_dir:
  desc: null
  value: output_custom/Beauty/Cluster_Attention
data_name:
  desc: null
  value: Beauty
do_eval:
  desc: null
  value: false
model_idx:
  desc: null
  value: UPTRec_Cluster_Attention_5
gpu_id:
  desc: null
  value: '0'
embedding:
  desc: null
  value: false
attention_map:
  desc: null
  value: false
vanilla_attention:
  desc: null
  value: false
alignment_loss:
  desc: null
  value: true
noise_ratio:
  desc: null
  value: 0.0
training_data_ratio:
  desc: null
  value: 1.0
augment_type:
  desc: null
  value: random
tao:
  desc: null
  value: 0.2
gamma:
  desc: null
  value: 0.7
beta:
  desc: null
  value: 0.2
temperature:
  desc: null
  value: 1.0
n_views:
  desc: null
  value: 2
contrast_type:
  desc: null
  value: None
attention_type:
  desc: null
  value: Cluster
context:
  desc: null
  value: item_embedding
num_intent_clusters:
  desc: null
  value: '64'
seq_representation_type:
  desc: null
  value: concatenate
seq_representation_instancecl_type:
  desc: null
  value: concatenate
warm_up_epoches:
  desc: null
  value: 0
de_noise:
  desc: null
  value: false
model_name:
  desc: null
  value: UPTRec
hidden_size:
  desc: null
  value: 64
num_hidden_layers:
  desc: null
  value: 2
num_attention_heads:
  desc: null
  value: 2
hidden_act:
  desc: null
  value: gelu
attention_probs_dropout_prob:
  desc: null
  value: 0.5
hidden_dropout_prob:
  desc: null
  value: 0.5
initializer_range:
  desc: null
  value: 0.02
max_seq_length:
  desc: null
  value: 50
cluster_train:
  desc: null
  value: 5
save_pt:
  desc: null
  value: 'False'
lr:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 512
epochs:
  desc: null
  value: 2000
patience:
  desc: null
  value: 500
no_cuda:
  desc: null
  value: false
log_freq:
  desc: null
  value: 1
seed:
  desc: null
  value: 1
cf_weight:
  desc: null
  value: 0.1
rec_weight:
  desc: null
  value: 1.0
intent_cf_weight:
  desc: null
  value: 0.3
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
device:
  desc: null
  value: cuda:1
cuda_condition:
  desc: null
  value: true
data_file:
  desc: null
  value: data/Beauty.txt
item_size:
  desc: null
  value: 12103
mask_id:
  desc: null
  value: 12102
log_file:
  desc: null
  value: output_custom/Beauty/Cluster_Attention/UPTRec-Beauty-UPTRec_Cluster_Attention_5-64-512.txt
train_matrix:
  desc: null
  value: "  (0, 1)\t1\n  (0, 2)\t1\n  (0, 3)\t1\n  (1, 6)\t1\n  (1, 7)\t1\n  (1, 8)\t\
    1\n  (1, 9)\t1\n  (1, 10)\t1\n  (2, 4)\t1\n  (2, 12)\t1\n  (2, 13)\t1\n  (2, 14)\t\
    1\n  (2, 15)\t1\n  (2, 16)\t1\n  (2, 17)\t1\n  (3, 20)\t1\n  (3, 21)\t1\n  (3,\
    \ 22)\t1\n  (3, 23)\t1\n  (4, 4)\t1\n  (4, 25)\t1\n  (4, 26)\t1\n  (4, 27)\t1\n\
    \  (4, 28)\t1\n  (4, 29)\t1\n  :\t:\n  (22355, 11716)\t1\n  (22356, 3545)\t1\n\
    \  (22356, 3550)\t1\n  (22356, 5595)\t1\n  (22357, 1849)\t1\n  (22357, 3025)\t\
    1\n  (22357, 6466)\t1\n  (22357, 11785)\t1\n  (22358, 11794)\t1\n  (22358, 11811)\t\
    1\n  (22358, 12042)\t1\n  (22359, 3023)\t1\n  (22359, 5595)\t1\n  (22359, 6466)\t\
    1\n  (22359, 9744)\t1\n  (22359, 10747)\t1\n  (22360, 9268)\t1\n  (22360, 11803)\t\
    1\n  (22360, 12055)\t1\n  (22361, 3023)\t1\n  (22361, 9744)\t1\n  (22361, 10607)\t\
    1\n  (22362, 3025)\t1\n  (22362, 6466)\t1\n  (22362, 9744)\t1"
checkpoint_path:
  desc: null
  value: output_custom/Beauty/Cluster_Attention/UPTRec-Beauty-UPTRec_Cluster_Attention_5-64-512.pt
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714899190.0
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      - 61
      4: 3.8.18
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
