#----enviroment settings-----
use_gpu: True
gpu_id: 0
save_dataset: True
seed: 1

#----data settings----
#MovieLens, Amzaon

data_path: dataset/
field_seperator: "\t"
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
# ITEM_ID_FIELD: product_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]

MAX_ITEM_LIST_LENGTH: 50

### ----Filtering----- ###
user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"

# ------Training and evaluation-------
epochs: 500
train_batch_size: 256
eval_batch_size: 256
learner: adam
learning_rate: 0.001 
train_neg_sample_args: ~
stopping_step: 40
eval_step: 1


eval_args:
    group_by: user
    order: TO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['NDCG', 'Hit']
topk: [5,10,15,20]
valid_metric: 'NDCG@10' 


### Model 
k: 100
