#----enviroment settings-----
use_gpu: True
gpu_id: 0
save_dataset: True
seed: 1

#----data settings----
#MovieLens, Amzaon

data_path: dataset/
field_seperator: "\t"
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
# ITEM_ID_FIELD: product_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]

MAX_ITEM_LIST_LENGTH: 50
rm_dup_inter: first

filter_inter_by_user_or_item: True

user_inter_num_interval: "[5,200)"
item_inter_num_interval: "[5,inf)"

# ------Training and evaluation-------
epochs: 1000
train_batch_size: 512
eval_batch_size: 512
learner: adam
learning_rate: 0.001 
train_neg_sample_args: ~
stopping_step: 40
eval_step: 1


eval_args:
    group_by: user
    order: TO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['NDCG', 'Hit']
topk: [5,10,15,20]
valid_metric: 'NDCG@10' 

# model config
hidden_size: 64
n_layers: 2
hidden_act: 'gelu'
loss_type: 'CE'
