#----enviroment settings-----
use_gpu: false
save_dataset: True
seed: 2020

#----data settings----
#MovieLens, Amzaon
data_path: dataset/
field_seperator: "\t"
USER_ID_FIELD: user_id
# ITEM_ID_FIELD: item_id
ITEM_ID_FIELD: product_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]

MAX_ITEM_LIST_LENGTH: 50
rm_dup_inter: first

filter_inter_by_user_or_item: True

user_inter_num_interval: "[5,200)"
item_inter_num_interval: "[5,inf)"

min_user_inter_num: 5
min_item_inter_num: 5

# ------Training and evaluation-------
epochs: 3
train_batch_size: 32
eval_batch_size: 32
learner: adam
learning_rate: 0.001 
train_neg_sample_args: ~
stopping_step: 10
eval_step: 1


eval_args:
    group_by: user
    order: TO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['Recall', 'NDCG', 'Hit', 'Precision']
topk: [1,5,10]
valid_metric: NDCG@10

# model config
embedding_size: 64
hidden_size: 128
num_layers: 2
dropout_prob: 0.5
loss_type: 'CE'
